language: python
python:
  - '3.5'

script:
  - tox
notifications:
  slack:
    secure: QVhlHVTMjtt5xwpF2936+gdB3iriawm4DyKd3kWMD8IPvXER+z7xSti41FQVIP99bkkfmHxvmBu/e7Sofvn7W/aK4LnZ31p1AkvnR7v0VGH6lZ8KbJFk5CJV5cR8pDRigPOB3D4i09MhiBtTdRBc/rNFiBWmJ0mwze6K8y5Bm5Mg/Ai26Fn/bMs9nxxoTDzcjgKMHelKwUatMaTCT2E1mKJftJ7KNXK5b0AoAd0T15nQ/z/0RaiRc6NKypr14kuNFJARVRR48FfSNsGKhLNy1dJKEAdPiOrD4I9VC6tbnOwhG6pc9zLD6sUlmIt6bdmJQTutN8WG06PSD5SiX78KZqsxpsfvkXsDulw+lwlI5Fb97G9MLNPVxTou2jyymm0p/DEJa9S+lDrzuuMEgipYRJxl7KtOf9kib+A4nYlQUgqXm9TSJsTpWo00+oF+EuKmKz0mqwbGXDWqZ0L0InXZ4hY0j6EYLpt/47BORBevNJjn1UDzWfDOAa0h55YLKuKiRcxuLofGeVoBES0gYdM2Q9dMWV/9qQPI5LiAFjvl+yU4rY1iue67KbPUxqaInUWaMofAgY0su2EYsevndQaWUrngkuI8HnxGNeTVMFJAzGDUm28FfbWUfHs6a7Muf8DkHRNtXbJDp6+yAwuFMYPxOTFgzhctNgRKx5JRjbvYmTU=
  email:
    recipients:
      - fab@mozaik.life
    on_success: change
    on_failure: always
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.tar.gz)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
  - echo ls /home/travis/build/millerf/django-channels2-jsonrpc
deploy:
    - provider: pypi
      user: __token__
      password:
        secure: pypi-AgEIcHlwaS5vcmcCJDU4OWYxZjg1LTk3YmYtNGYyNS05NjFkLTcwZGUwODU1NGRkMAACSXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkamFuZ28tY2hhbm5lbHMyLWpzb25ycGMiXX0sICJ2ZXJzaW9uIjogMX0AAAYgYQv1wLEKjrM9XfiaWIkL-S9dveOmXxvhYnLnhxA8OAc
      on:
        tags: true
        distributions: sdist bdist_wheel
        repo: millerf/django-channels2-jsonrpc
addons:
    code_climate:
        repo_token: c733d1abd2f685b1f6ecf418b7c507a007bf49181b3139be7c558c84c314c64d
